// Generated by CoffeeScript 1.3.1
(function() {
  var Bloat;

  Bloat = (function() {

    Bloat.name = 'Bloat';

    function Bloat(args) {
      this.raw_html = "";
    }

    Bloat.prototype.literal = function(text) {
      this.raw_html += text;
      return this;
    };

    Bloat.prototype.div = function(options) {
      this.raw_html += "<div";
      if (!(Bloat.null_or_empty(options) || Bloat.null_or_empty(options.id))) {
        this.raw_html += " id=\"" + options.id + "\"";
      }
      if (!(Bloat.null_or_empty(options) || Bloat.null_or_empty(options["class"]))) {
        this.raw_html += " class=\"" + options["class"] + "\"";
      }
      this.raw_html += ">";
      return this;
    };

    Bloat.prototype.$div = function() {
      this.raw_html += "</div>";
      return this;
    };

    Bloat.prototype.span = function(options) {
      this.raw_html += "<span>";
      return this;
    };

    Bloat.prototype.$span = function() {
      return this.raw_html += "</span>";
    };

    Bloat.prototype.br = function() {
      this.raw_html += "<br />";
      return this;
    };

    Bloat.prototype.p = function(options) {
      this.raw_html += "<p>";
      return this;
    };

    Bloat.prototype.$p = function() {
      this.raw_html += "</p>";
      return this;
    };

    Bloat.prototype.table = function(options) {
      this.raw_html += "<table>";
      return this;
    };

    Bloat.prototype.$table = function() {
      this.raw_html += "</table>";
      return this;
    };

    Bloat.prototype.tr = function(options) {
      this.raw_html += "<tr>";
      return this;
    };

    Bloat.prototype.$tr = function() {
      return this.raw_html += "</tr>";
    };

    Bloat.prototype.td = function(options) {
      this.raw_html += "<td>";
      return this;
    };

    Bloat.prototype.$td = function() {
      this.raw_html += "</td>";
      return this;
    };

    Bloat.prototype["export"] = function() {
      return this.raw_html;
    };

    Bloat.null_or_empty = function(x) {
      return x === null || x === "" || x === void 0;
    };

    return Bloat;

  })();

  window.Bloat = Bloat;

}).call(this);
