// Generated by CoffeeScript 1.3.3
(function() {
  var jBlote;

  jBlote = (function() {

    function jBlote(args) {
      this.raw_html = "";
    }

    jBlote.prototype.literal = function(text) {
      this.raw_html += text;
      return this;
    };

    jBlote.prototype.a = function(options) {
      this.raw_html += this.open_tag('a', options);
      return this;
    };

    jBlote.prototype.br = function() {
      return this.raw_html += this.simple_tag('br');
    };

    jBlote.prototype["export"] = function() {
      return this.raw_html;
    };

    jBlote.simple_tag = function(tag_name) {
      this.raw_html += "<" + tag_name + " />";
      return this;
    };

    jBlote.open_tag = function(tag_name, options) {
      this.raw_html += "<" + tag_name;
      this.raw_html += apply_options(options);
      this.raw_html += ">";
      return this;
    };

    jBlote.close_tag = function(tag_name) {
      this.raw_html += "</" + tag_name + ">";
      return this;
    };

    jBlote.apply_options = function(options) {
      var key, text, value;
      text = "";
      for (key in options) {
        value = options[key];
        text += " " + key + "=\"" + value("\"");
      }
      return text;
    };

    jBlote.null_or_empty = function(x) {
      return x === null || x === "" || x === void 0;
    };

    return jBlote;

  })();

  window.Blote = new jBlote;

}).call(this);
